### ISSUE TITLE
Screenshot in the README of 12 hour format is incorrect

### ISSUE THREAD

**Issue by lee-dohm** [b3by/atom-clock#1]
Or maybe it is a bug in the package itself?

![ampm](https://cloud.githubusercontent.com/assets/1038121/11217121/991954e0-8d03-11e5-84b3-537c5fe2ca44.png)

12-hour format doesn't go above 12 :grinning:

**Comment by b3by** [comment]
Thanks for the mention, I did not realise I used the wrong format when taking the screenshot. So far, the package should not be bugged (at least, I hope so!).
