### ISSUE TITLE
markdown-scroll-sync

### ISSUE THREAD

**Issue by snakelis** [b3by/atom-clock#12]

**Comment by b3by** [comment]
I'm sorry, could you please give me some extra details about this issue?

**Comment by b3by** [comment]
I assume this issue was erroneously opened on this repository. I'm closing it for now.

**Comment by snakelis** [comment]
I am sorry if I upset you.This comment may be my careless reply.my English is so poor.I wish you an early settlement of the problem

2017-01-03 

m13017393354 



发件人：Antonio Bevilacqua <notifications@github.com>
发送时间：2016-12-31 18:31
主题：Re: [b3by/atom-clock] markdown-scroll-sync (#12)
收件人："b3by/atom-clock"<atom-clock@noreply.github.com>
抄送："snakelis"<m13017393354@163.com>,"Author"<author@noreply.github.com>

I assume this issue was erroneously opened on this repository. I'm closing it for now.
