### ISSUE TITLE
Missing the clock icon.

### ISSUE THREAD

**Issue by Mine-MuYan** [b3by/atom-clock#21]
When I don't select,on the left of the time ,it looks lack something.

![unselect](https://cloud.githubusercontent.com/assets/23254569/23491523/b59c069a-ff39-11e6-9378-1b4cb934d7a5.png)

When I select ,the time move to the left and the clock icon missed.
![2](https://cloud.githubusercontent.com/assets/23254569/23491720/f4bd846a-ff3a-11e6-9336-29e03248e053.png)

**Comment by b3by** [comment]
Thank you for that!
I think this is somehow related to #20 so I have to look into it. I'll probably fix them in the weekend, or tomorrow!
