### ISSUE TITLE
Date text is rendered lower than other elements in status bar

### ISSUE THREAD

**Issue by AndrewBastin** [b3by/atom-clock#27]
Date text is rendered lower than other elements in the status bar as of Atom Version 1.17.0

![atom](https://cloud.githubusercontent.com/assets/9131943/26274090/556edee2-3d5e-11e7-8d13-80a3b7c20991.PNG)

**Comment by b3by** [comment]
Thank you for this. I'll look into it ASAP, as the rendering position has been an issue for quite a while. On which platform you experienced this problem?

**Comment by AndrewBastin** [comment]
I am experiencing this in Windows...

**Comment by b3by** [comment]
I'm fixing this right now. It seems to be a thing on OS X as well.

**Comment by frasertmay** [comment]
Removing all the CSS and adding the `inline-block` class to the clock element seemed to fix it for me.

`atom-clock.less`:
```less
@import "ui-variables";

.atom-clock {
  // display: inline-block;
  // margin-left: 1em;
  // margin-right: 0.5em;
  // position: relative;
  // vertical-align: middle;
  //
  // .span {
  //   text-align: left;
  // }
}
```

`atom-clock-view.js`:

```javascript
drawElement() {
    this.element = document.createElement('div')
    this.element.className = 'atom-clock inline-block'
    this.element.appendChild(document.createElement('span'))

    this.statusBar.addRightTile({
      item: this.element,
      priority: -1
    })
  }
```
See before (top) and after (bottom)
![screen shot 2017-05-25 at 11 33 00](https://cloud.githubusercontent.com/assets/3003251/26473759/20c0a068-41a5-11e7-8c73-f09f9dba9de1.png)

**Comment by b3by** [comment]
I actually did not change the code, just the style file, adding some stuff for the icon. The result seems to be pretty much the same.

```
@import "ui-variables";
@import "octicon-mixins";

.atom-clock {
  display: inline-block;
  position: relative;

  .icon:before {
    .icon-size(14px);
    top: 1px;
    margin-right: 3px;
  }

}
```

**Comment by b3by** [comment]
Actually, the `atom-clock` class should also have `margin-left` set to `@component-padding`, so that there will be space between the clock and the element to the left.

**Comment by b3by** [comment]
Seems to be reasonable. I still don't know whether this is the right solution, or the css style is useless.

![screenshot 2017-05-26 00 05 48](https://cloud.githubusercontent.com/assets/472900/26474129/30d5e40c-41a7-11e7-9531-33391427e5f9.png)

**Comment by frasertmay** [comment]
The `inline-block` class seems to add `margin-left: 1.5em` so maybe the CSS could just be used to move the icon around. Up to you I guess
