### ISSUE TITLE
Clock position with GitHub package

### ISSUE THREAD

**Issue by frasertmay** [b3by/atom-clock#32]
With one of the latest Atom updates they seem to have added a GitHub package which adds items to the status bar so the clock is no longer the furthest to the right.

![screen shot 2017-06-18 at 09 40 19](https://user-images.githubusercontent.com/3003251/27259413-df77ed78-540a-11e7-89e4-43500cc3473e.png)

This seems to be because atom-clock uses `priority: -1` when creating the status bar tile ([code](https://github.com/b3by/atom-clock/blob/master/lib/atom-clock-view.js#L62)) whereas the GitHub package uses `priority: -50` ([code](https://github.com/atom/github/blob/master/lib/views/status-bar.js#L33)).

I suppose if you want the clock to always be the furthest to the right we could just use `priority: -1000` or something, maybe this could be made into something the user could control?

**Comment by b3by** [comment]
Thanks for raising the issue. I guess there is no way of being sure the clock is always placed at the very right of the status bar, and yet, I wouldn't really turn this into another setting item.
I guess, for now, I'll just push a lower priority (`-500`) and bump the package version.
