### ISSUE TITLE
Calculate day to next Fiscal Quarters

### ISSUE THREAD

**Issue by git001** [b3by/atom-clock#37]
Hi.

how can I calculate the days to the next Fiscal Quarters ?

http://momentjs.com/docs/#/plugins/fquarter/

**Comment by frasertmay** [comment]
As atom-clock does not use the `moment-fquarter` plugin mentioned in the docs you linked it is not currently possible to do this

**Comment by git001** [comment]
Thanks @frasertmay .

Is it planned to add it?
If you want you can see this as request for enhancement ;-)

**Comment by frasertmay** [comment]
It's probably not in any current plans so it would be up to the owner @b3by to decide whether it's something he wants to do - however you're welcome to fork the repo and include it yourself.

**Comment by git001** [comment]
I will take a look

**Comment by frasertmay** [comment]
I've detailed in my [comment](https://github.com/robgallen/moment-fquarter/issues/20#issuecomment-312627344) on your issue on `moment-fquarter` how one would go about trying to do what you want to do.

As for doing this in `atom-clock`, as I mentioned earlier it is currently not possible as we only allow the user to change the format the current time is displayed in, not allow them to display another time.

**Comment by b3by** [comment]
Thank you guys for turning every rock on this. The solution @frasertmay suggested in the related issue on `fquarter` is smart. However, I'm not sure this is a feature I want in the package. This is a very specific feature, that maybe falls a bit out of the scope of a simple clock. Also, the clock is something that actually needs constant refreshing and re-rendering in the status bar, while the days to the next fiscal quarter don't really take that complexity.

This sounds like something that could be implemented in a separate package, maybe something that just shows a popup, triggered by a keybinding, with the days to the next quarter in it.

Anyway, thank you very much for the suggestion!
