### ISSUE TITLE
Tooltip alert for UTC time

### ISSUE THREAD

**Issue by b3by** [b3by/atom-clock#42]
It could be helpful to have an UTC indicator in the tooltip, that should show when the UTC time is enabled. Assuming the tooltip time format is still `LLLL`, the indicator could be something like:

```
(UTC) Wednesday, August 30, 2017 11:21 AM
```

**Comment by frasertmay** [comment]
So something like this?

Local:
![screen shot 2017-08-30 at 11 58 27](https://user-images.githubusercontent.com/3003251/29869399-b16b83a0-8d7a-11e7-95ac-8b7862a99ef9.png)

UTC:
![screen shot 2017-08-30 at 11 58 42](https://user-images.githubusercontent.com/3003251/29869412-b7d69004-8d7a-11e7-88b8-236a34a340e8.png)

**Comment by b3by** [comment]
Exactly. I guess there's already a PR on the way. :1st_place_medal:

**Comment by frasertmay** [comment]
Yeah I'll make one in a bit. I'm just thinking about adding a class to the time element and/or tooltip when in UTC mode so the user can customise it how they want including adding text before or after using the `content` property in their CSS.

**Comment by b3by** [comment]
That's a good point. Probably a `atom-clock-utc-time` class in the time element could be enough I guess. The tooltip can be picked with its own `atom-clock-tooltip` class, so this should be quite easy to edit.

**Comment by frasertmay** [comment]
I've added a `atom-clock-utc` class to the `atom-clock` element and the `atom-clock-tooltip` element so now you can do this. I think this is probably a better solution than forcing people to have `(UTC)` especially if they don't have the tooltip enabled.

**Local**:
![screen shot 2017-08-30 at 14 12 06](https://user-images.githubusercontent.com/3003251/29874015-47402dba-8d8d-11e7-960d-0057a74e6385.png)

**UTC**:
![screen shot 2017-08-30 at 14 12 22](https://user-images.githubusercontent.com/3003251/29874016-47410078-8d8d-11e7-8622-aa12b75ec064.png)

**Comment by b3by** [comment]
Primo! Very well done, thank you! This'll keep things tidy.
I guess I'll add some of these snippets for personalizing the clock in the README file!!

**Comment by frasertmay** [comment]
Yeah I'll add some stuff into the README now and submit the PR
