### ISSUE TITLE
Just an idea I had now with the last update...

### ISSUE THREAD

**Issue by GiovanniSM20** [b3by/atom-clock#47]
I think a good idea would be to put a kind of alarm on the clock since sometimes we end up putting the edit in full screen causing that we lose the notion of the hour and we could define some hour and on this hour would appear a "pop-up" with the alarm...

**Comment by b3by** [comment]
Thank you for the suggestion. A timer is something that can be good indeed, but it is out of the scope of the package purpose.
If you are interested in having a timer to keep track of how much you've worked, there are a few packages out there that seem to be great for this:

- [tomato-timer](https://atom.io/packages/tomato-timer)
- [tomatimer](https://atom.io/packages/tomatimer)
- [pomodoro](https://atom.io/packages/pomodoro)
- [break-time](https://atom.io/packages/break-time)

Hope this helps!

**Comment by GiovanniSM20** [comment]
It would not be to see how much I worked like wakatime for example. But from the plugins you sent, you gave to satisfy the idea, thank you! :octocat:
