### ISSUE TITLE
Did you get my message?

### ISSUE THREAD

**Issue by CatherineMaddenUXDX** [b3by/atom-clock#51]
Hi Antonio,

I've sent you an email on UXDX a few days ago and I'm wondering if you had a chance to read it; I'm afraid it might have been marked as spam.

I would like to say thank you for being involved in Open Source and discuss something regarding our conference.

Could you please double check your email or drop me a message at catherine@uxdxconf.com?

Thanks in advance,
Catherine

**Comment by b3by** [comment]
This should be sorted! Nice one anyway, works better than emails!
Thanks for the notification!
