### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by AnetteMM** [b3by/atom-clock#61]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (<embedded>:14:61659)
MarkerLayer.markRange (<embedded>:14:72468)
DisplayMarkerLayer.markBufferRange (<embedded>:14:1091810)
TextEditor.markBufferRange (<embedded>:11:28288)
SearchModel.start (C:\Users\PC\.atom\packages\incremental-search\lib\search-model.coffee:79:45)
new SearchModel (C:\Users\PC\.atom\packages\incremental-search\lib\search-model.coffee:34:12)
```

**Comment by b3by** [comment]
Thank you for reporting the issue, but I am not sure I'm following. Is it related to the `atom-clock` package?

**Comment by b3by** [comment]
As there was no follow-up, I'm closing this for now.
