### ISSUE TITLE
@v0.0.8, on Atom 1.10-beta, seconds not updating (:ss)

### ISSUE THREAD

**Issue by jiminikiz** [b3by/atom-clock#7]
Doesn't seem like the seconds update every second. Not a big deal for me, but thought I'd let you know. Probably only affects atom-beta.

Also using Windows if that helps.

**Comment by b3by** [comment]
Thanks a lot for the alert, will look into this asap.

**Comment by b3by** [comment]
Seconds are refreshed with Atom Beta on Mac. I'm guessing this is something platform-related.

**Comment by b3by** [comment]
Is this bug still live @jiminikiz?

**Comment by jiminikiz** [comment]
My apologies, it totally was working, I needed to update the interval to every second, thanks so much for being on top of it!

**Comment by b3by** [comment]
No hassle, thanks for closing it!
